### ISSUE TITLE
Handling of corrupt world-state messages

### ISSUE THREAD

**Issue by TimZaman** [TimZaman/dotaservice#1]
This crashed both the dotaservice as well as the client. The worldstate that was sent was incomplete, probably because it was [intentionally] killed while sending the worldstate.

## Service
```
(python) action= {'actionType': 'DOTA_UNIT_ORDER_MOVE_TO_POSITION', 'moveToLocation': {'location': {'x': 6852.0, 'y': -5764.0, 'z': 0.0}}, 'dota_time': 109.81683349609375}
Script function 'Think' on bot npc_dota_hero_nevermore took 7.483ms
(py) worldstate @ dotatime=110.81704711914062, gamestate=5
DotaService::step()
(python) action= {'actionType': 'DOTA_UNIT_ORDER_MOVE_TO_POSITION', 'moveToLocation': {'location': {'x': 6852.0, 'y': -5764.0, 'z': 0.0}}, 'dota_time': 110.81704711914062}
Script function 'Think' on bot npc_dota_hero_nevermore took 7.549ms
(py) worldstate @ dotatime=111.8172607421875, gamestate=5
DotaService::reset()
config=
 host_timescale: 10
ticks_per_observation: 30
render: false

kill: 30495: No such process
Application error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpclib/server.py", line 327, in request_handler
    await method.func(stream)
  File "/Users/tzaman/Drive/code/dotaservice/dotaservice/dotaservice.py", line 305, in reset
    game_id=config.game_id,
  File "/Users/tzaman/Drive/code/dotaservice/dotaservice/dotaservice.py", line 75, in __init__
    self.bot_path = self._create_bot_path()
  File "/Users/tzaman/Drive/code/dotaservice/dotaservice/dotaservice.py", line 129, in _create_bot_path
    assert len(lua_files) == 5
AssertionError
/Users/tzaman/Library/Application Support/Steam/SteamApps/common/dota 2 beta/game/dota.sh: line 104: 30491 Killed: 9               ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Task exception was never retrieved
future: <Task finished coro=<DotaGame._worldstate_listener() done, defined at /Users/tzaman/Drive/code/dotaservice/dotaservice/dotaservice.py:241> exception=error('unpack requires a buffer of 4 bytes')>
Traceback (most recent call last):
  File "/Users/tzaman/Drive/code/dotaservice/dotaservice/dotaservice.py", line 253, in _worldstate_listener
    parsed_data = await self._data_from_reader(reader)
  File "/Users/tzaman/Drive/code/dotaservice/dotaservice/dotaservice.py", line 230, in _data_from_reader
    n_bytes = unpack("@I", data)[0]
struct.error: unpack requires a buffer of 4 bytes
```

## Client
```
(..)
ep=351 reward sum=21237.75
last hero loc dotatime=111.8172607421875, x=6240.0, y=-5920.0
last hero loc dotatime=111.8172607421875, x=6752.0, y=-5664.0
Traceback (most recent call last):
  File "client.py", line 263, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "client.py", line 175, in main
    state = await env.reset(config)
  File "/usr/local/lib/python3.7/site-packages/grpclib/client.py", line 556, in __call__
    return await stream.recv_message()
  File "/usr/local/lib/python3.7/site-packages/grpclib/client.py", line 304, in recv_message
    await self.recv_initial_metadata()
  File "/usr/local/lib/python3.7/site-packages/grpclib/client.py", line 246, in recv_initial_metadata
    self._raise_for_grpc_status(headers_map, optional=True)
  File "/usr/local/lib/python3.7/site-packages/grpclib/client.py", line 215, in _raise_for_grpc_status
    raise GRPCError(grpc_status_enum, status_message)
grpclib.exceptions.GRPCError: (<Status.UNKNOWN: 2>, 'Internal Server Error')
```

**Comment by Nostrademous** [comment]
I think I ran into this issue before and it had to do with how Dota2 prepares the protobuf messages to send out and how I was receiving data on the socket before it was ready leading me to read invalid amounts.

I haven't dove deep into your code enough to see where you read the protobufs from the client yet to see  how you implemented the logic.

**Comment by Nostrademous** [comment]
This is where I would check to make sure the value is valid. I had an issue here before.
https://github.com/TimZaman/dotaservice/blob/master/dotaservice/dotaservice.py#L259

**Comment by TimZaman** [comment]
Its all async so it can fail whereever it wants to. Currently have the
dotaervice running for 4 days in 8 containers, arouns 30.000 games played
so far.

**Comment by Nostrademous** [comment]
Cool, that's great. I am not sure of the reader you are using... but the issue for me went away when i used select to check the socket state.

https://github.com/pydota2/pydota2/commit/0a93e3cabf3bb10eac0ee40a7877565445274288

check the proto_connector.py changes

**Comment by TimZaman** [comment]
Nice, i cant use that though as dotaservice is entirely asynchronous

**Comment by TimZaman** [comment]
Fixed
