### ISSUE TITLE
get_unit returns None

### ISSUE THREAD

**Issue by TimZaman** [TimZaman/dotaservice#2]
Below error probably caused by the Hero not being present in the world state (wut?!)

## Client
```
x=-2406, y=-796, reward=0.0
Traceback (most recent call last):
  File "client.py", line 306, in <module>
    asyncio.run(main())
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "client.py", line 241, in main
    reward = get_reward(prev_state=prev_state, state=state)
  File "client.py", line 77, in get_reward
    xp = get_total_xp(level=unit.level, xp_needed_to_level=unit.xp_needed_to_level)
AttributeError: 'NoneType' object has no attribute 'level'
```

# Server
```
(...)
(python) action= {'actionType': 'DOTA_UNIT_ORDER_MOVE_TO_POSITION', 'moveToLocation': {'location': {'x': -2355.25537109375, 'y': -905.2532958984375, 'z': 0.0}}, 'dota_time': -16.234458923339844}
Script function 'Think' on bot npc_dota_hero_nevermore took 9.823ms
(py) worldstate @ dotatime=-15.234474182128906, gamestate=4
DotaService::step()
(python) action= {'actionType': 'DOTA_UNIT_ORDER_MOVE_TO_POSITION', 'moveToLocation': {'location': {'x': -2105.71923828125, 'y': -1095.6365966796875, 'z': 0.0}}, 'dota_time': -15.234474182128906}
Script function 'Think' on bot npc_dota_hero_nevermore took 8.761ms
(py) worldstate @ dotatime=-14.234489440917969, gamestate=4
DotaService::step()
(python) action= {'actionType': 'DOTA_UNIT_ORDER_MOVE_TO_POSITION', 'moveToLocation': {'location': {'x': -2398.65966796875, 'y': -497.1832275390625, 'z': 0.0}}, 'dota_time': -14.234489440917969}
Script function 'Think' on bot npc_dota_hero_nevermore took 8.750ms
(py) worldstate @ dotatime=-13.234504699707031, gamestate=4
/Users/tzaman/dev/dotaservice/dotaservice/dotaservice.py:243: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  parsed_data.ParseFromString(data)
(py) worldstate @ dotatime=0.0, gamestate=0
```

**Comment by TimZaman** [comment]
Fixed
