### ISSUE TITLE
Dotaservice's `reset` crash: worlstate related?

### ISSUE THREAD

**Issue by TimZaman** [TimZaman/dotaservice#3]
# Server:
```
Traceback (most recent call last):
  File "/root/dotaservice/dotaservice/dotaservice.py", line 261, in _worldstate_listener
    parsed_data = await self._data_from_reader(reader)
  File "/root/dotaservice/dotaservice/dotaservice.py", line 243, in _data_from_reader
    parsed_data.ParseFromString(data)
google.protobuf.message.DecodeError: Error parsing message
LUARDY	{"step":30,"dota_time":-88.933349609375}
(lua) looking for loadfile =	bots/live_config_auto
(py) lua_config =  {'step': 30, 'dota_time': -88.933349609375}
(py) lua config received= {'step': 30, 'dota_time': -88.933349609375}
(py) writing live config= {'calibration_dota_time': -89.23334503173828}
(lua) live_config =	{ ["calibration_dota_time"] = -89.233345031738,} 
Script function 'Think' on bot npc_dota_hero_nevermore took 361.868ms
DotaService::step()
(python) action= {'actionType': 'DOTA_UNIT_ORDER_MOVE_TO_POSITION', 'moveToLocation': {'location': {'x': -6400.0, 'y': -6400.00390625, 'z': 0.0}}, 'dota_time': -89.23334503173828}
Request was cancelled
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/grpclib/server.py", line 327, in request_handler
    await method.func(stream)
  File "/root/dotaservice/dotaservice/dotaservice.py", line 362, in step
    data = await self.dota_game.worldstate_queue.get()
  File "/usr/lib/python3.7/asyncio/queues.py", line 159, in get
    await getter
concurrent.futures._base.CancelledError

```

**Comment by TimZaman** [comment]
Fixed in #524d2332cce226c3e7a54c902dc680c2cb90380a
